set(CMAKE_CXX_STANDARD 23)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/build/${CMAKE_BUILD_TYPE})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})

set(CMAKE_PDB_OUTPUT_DIRECTORY "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/debug files")
set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS_RELEASE} /MANIFEST:NO /DEBUG") # debug for generating pdb files for profiling
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
set(CMAKE_VS_PLATFORM_NAME "x64")

if (CMAKE_BUILD_TYPE MATCHES Debug)
    set(DEBUG_SUFFIX "d")
endif (CMAKE_BUILD_TYPE MATCHES Debug)

add_compile_definitions(ENGINE_PLATFORM_WINDOWS ENGINE_DEBUG)
